[project]
name = "landa"
authors = [
    { name = "ALYF GmbH", email = "hallo@alyf.de" },
]
description = "Datenmanagementsystem des Landesverband Sächsischer Angler e. V."
requires-python = ">=3.7"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "thefuzz~=0.19.0",
    "pandas~=1.5.3"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"
