def get_custom_fields():
	return {
		"Address": [
			{
				"fieldname": "address_2",
				"insert_after": "address_info_text",
				"fieldtype": "Section Break",
			},
			{
				"label": "Address Info Text",
				"fieldname": "address_info_text",
				"insert_after": "address_details",
				"fieldtype": "HTML",
				"options": "<p>Das Formular für Adressen bezieht sich in LANDA auf einen Ort, also z. B. ein Wohnhaus oder ein Vereinsbüro. Es ist nicht (!) mit einer Person verknüpft. </p>\n\n<p>Das bedeutet, die Adresse beinhaltet in ihrer einfachsten Form nur Straße, Hausnummer, PLZ und Ort, aber nicht den Namen des Vereins und/ oder des Ansprechpartners. Diese werden im Formular <b><a href='/app/contact'>Kontakt </a></b> hinterlegt und erst bei der Adressierung zusammengeführt. </p>\n\n<p>Diese Trennung von Adresse und Kontakt ermöglicht es, Adressen sowohl für ein Mitglied als auch für einen Verein zu verwenden, ohne doppelte Adresspflege zu betreiben.</p>\n\n<p>Damit man Adressen bei der Adressierung (z. B. für Lieferscheine) bzw. in einer Suche leichter zuordnen kann, ist es möglich, eine Adressbezeichnung anzugeben. Diese taucht nicht in der Adresse auf dem Brief auf und dient nur der Suche. Wenn man ein Mitglied, einen Verein oder ein Bestellkonto verknüpft mit der zu erstellenden Adresse verknüpft, ist es nicht notwendig, die Adressbezeichnung selbst zu wählen. Diese wird automatisch ausgefüllt, man darf aber die automatische Bezeichnung ändern (z. B. von \"AVE-003\" zu \"Büro im Vereinshaus Angelverein XY\")</p>\n\n<p>Mehr Infos zum Thema gibt es im Anleitungsvideo: <a href=\" https://youtu.be/JENu0W1NmlQ\" style=\"color: blue;\">Vereinsverwaltung #04 Adresse und Kontakt bearbeiten</a> und in den <a href=\"https://youtube.com/playlist?list=PLCG04RYNrML993pHOo16el5DGrKN5kCzh\" style=\"color: blue;\">LANDA Videotutorials - Vereinsverwaltung / Mitgliederverwaltung </a> </p>",
			},
			{
				"fieldname": "column_break_2",
				"insert_after": "address_2",
				"fieldtype": "Column Break",
			},
			{
				"label": "Customer",
				"fieldname": "customer",
				"insert_after": "organization",
				"fieldtype": "Link",
				"options": "Customer",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Is Your Company Address",
				"fieldname": "is_your_company_address",
				"insert_after": "linked_with",
				"fieldtype": "Check",
				"default": "0",
				"hidden": 1,
			},
			{
				"label": "LANDA Member",
				"fieldname": "landa_member",
				"insert_after": "customer",
				"fieldtype": "Link",
				"options": "LANDA Member",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "links",
				"fieldtype": "Link",
				"options": "Organization",
				"read_only": 1,
			},
			{
				"label": "Tax Category",
				"fieldname": "tax_category",
				"insert_after": "fax",
				"fieldtype": "Link",
				"options": "Tax Category",
				"hidden": 1,
			},
		],
		"Company": [
			{
				"label": "Bank name",
				"fieldname": "bank_name",
				"insert_after": "banking_account_information",
				"fieldtype": "Data",
			},
			{
				"label": "Banking Account and Legal Information",
				"fieldname": "banking_account_information",
				"insert_after": "parent_company",
				"fieldtype": "Section Break",
			},
			{
				"label": "Banking and Legal Info Text",
				"fieldname": "banking_and_legal_info_text",
				"insert_after": "column_break_18",
				"fieldtype": "HTML",
				"options": "Die hier eingetragenen Informationen werden hauptsächlich dazu verwendet diese auf Dokumenten auszugeben.",
			},
			{
				"label": "BIC",
				"fieldname": "bic",
				"insert_after": "iban",
				"fieldtype": "Data",
			},
			{
				"label": "CEO",
				"fieldname": "ceo",
				"insert_after": "column_break_15",
				"fieldtype": "Data",
			},
			{
				"fieldname": "column_break_15",
				"insert_after": "bic",
				"fieldtype": "Column Break",
			},
			{
				"fieldname": "column_break_18",
				"insert_after": "district_court",
				"fieldtype": "Column Break",
			},
			{
				"label": "Company",
				"fieldname": "company_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Company Info Text",
				"fieldname": "company_info_text",
				"insert_after": "company_info_section",
				"fieldtype": "HTML",
				"options": "<p>Regionalverbände sind in diesem System auch als Unternehmen hinterlegt, weil diese Artikel an die Vereine liefern, welche wiederum als Kunden hinterlegt sind.</p>\n\n<p>Eine Übersicht der Unternehmen finden Sie <b><a href=\"/app/company\">hier</a></b>.</p>",
			},
			{
				"label": "Company Register",
				"fieldname": "company_register",
				"insert_after": "ceo",
				"fieldtype": "Data",
			},
			{
				"label": "Delivery Note Information text",
				"fieldname": "delivery_note_information_text",
				"insert_after": "render_contact_name_first_in_address",
				"fieldtype": "Text Editor",
				"default": "\n",
			},
			{
				"label": "District Court",
				"fieldname": "district_court",
				"insert_after": "company_register",
				"fieldtype": "Data",
			},
			{
				"label": "Document Settings",
				"fieldname": "document_texts",
				"insert_after": "company_description",
				"fieldtype": "Section Break",
			},
			{
				"label": "IBAN",
				"fieldname": "iban",
				"insert_after": "bank_name",
				"fieldtype": "Data",
			},
			{
				"label": "Info Document Settings",
				"fieldname": "info_document_settings",
				"insert_after": "document_texts",
				"fieldtype": "HTML",
				"options": "<p>Einstellungen für die Darstellung von Dokumenten wie Rechnungen, Lieferscheinen und Retouren.<br/></p>\n\n",
			},
			{
				"label": "Invoice Information Text",
				"fieldname": "invoice_information_text",
				"insert_after": "delivery_note_information_text",
				"fieldtype": "Text Editor",
			},
			{
				"label": "Render contact name first in address",
				"fieldname": "render_contact_name_first_in_address",
				"insert_after": "info_document_settings",
				"fieldtype": "Check",
			},
			{
				"label": "Retoure Information Text",
				"fieldname": "retoure_information_text",
				"insert_after": "invoice_information_text",
				"fieldtype": "Text Editor",
			},
		],
		"Contact": [
			{
				"fieldname": "column_break_2",
				"insert_after": "contacts_2",
				"fieldtype": "Column Break",
			},
			{
				"label": "Contact Info",
				"fieldname": "contact_info",
				"insert_after": "contact_section",
				"fieldtype": "HTML",
				"options": "<p>Das Formular für Kontakt bezieht sich in LANDA auf eine Person, die man erreichen möchte. Es gibt Auskunft über Name und Vorname für die Adressierung sowie Telefonnummern und Emailadressen.</p>\n\n<p>Die Adresse wird nicht in diesem Formular, sondern im Formular <b><a href='/app/address'>Adresse</a></b> hinterlegt und Name und Anschrift werden erst bei der Adressierung zusammengeführt. Diese Trennung von Adresse und Kontakt ermöglicht es, Adressen sowohl für ein Mitglied als auch für einen Verein zu verwenden, ohne doppelte Adresspflege zu betreiben.</p>\n\n<p>Damit man Kontakte bei der Adressierung (z. B. für Lieferscheine) bzw. in einer Suche leichter zuordnen kann, ist es möglich, eine Kontaktbezeichnung anzugeben. Diese taucht nicht in Dokumenten auf und dient nur der Suche. Wenn man ein Mitglied, einen Verein oder ein Bestellkonto verknüpft mit dem zu erstellenden Kontakt verknüpft, ist es nicht notwendig, die Kontaktbezeichnung selbst zu wählen. Diese wird automatisch ausgefüllt, man darf aber die automatische Bezeichnung ändern (z. B. von \"Max Mustermann\" zu \"Max Mustermann junior, Schatzmeister\")</p>\n\n<p>Mehr Infos zum Thema gibt es im Anleitungsvideo: <a href=\" https://youtu.be/JENu0W1NmlQ\" style=\"color: blue;\">Vereinsverwaltung #04 Adresse und Kontakt bearbeiten</a> und in den <a href=\"https://youtube.com/playlist?list=PLCG04RYNrML993pHOo16el5DGrKN5kCzh\" style=\"color: blue;\">LANDA Videotutorials - Vereinsverwaltung / Mitgliederverwaltung </a> </p>",
			},
			{
				"fieldname": "contacts_2",
				"insert_after": "contact_info",
				"fieldtype": "Section Break",
			},
			{
				"label": "Customer",
				"fieldname": "customer",
				"insert_after": "landa_member",
				"fieldtype": "Link",
				"options": "Customer",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Is Billing Contact",
				"fieldname": "is_billing_contact",
				"insert_after": "is_primary_contact",
				"fieldtype": "Check",
				"hidden": 1,
			},
			{
				"label": "LANDA Member",
				"fieldname": "landa_member",
				"insert_after": "organization",
				"fieldtype": "Link",
				"options": "LANDA Member",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "unsubscribed",
				"fieldtype": "Link",
				"options": "Organization",
				"read_only": 1,
			},
		],
		"Customer": [
			{
				"label": "Billing and Shipping Defaults",
				"fieldname": "billing_and_shipping_defaults",
				"insert_after": "contact_html",
				"fieldtype": "Section Break",
				"depends_on": 'eval: frappe.user.has_role("Sales Master Manager")\n|| frappe.user.has_role("Sales User")\n|| doc.default_billing_contact\n|| doc.default_billing_address\n|| doc.default_shipping_contact\n|| doc.default_shipping_address',
			},
			{
				"label": "Buyer Reference",
				"fieldname": "buyer_reference",
				"insert_after": "language",
				"fieldtype": "Data",
			},
			{
				"fieldname": "column_break_41",
				"insert_after": "default_billing_address_html",
				"fieldtype": "Column Break",
			},
			{
				"label": "Billing Contact Not Required",
				"fieldname": "custom_billing_contact_not_required",
				"insert_after": "default_billing_address",
				"fieldtype": "Check",
			},
			{
				"label": "Customer",
				"fieldname": "customer_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Cutomer Info Text",
				"fieldname": "cutomer_info_text",
				"insert_after": "customer_info_section",
				"fieldtype": "HTML",
				"options": "<p>Vereine sind in diesem System auch als Kunden hinterlegt, weil diese Artikel bestellen und geliefert bekommen.</p>\n\n<p>Eine Übersicht der Kunden finden Sie <b><a href=\"/app/customer\">hier</a></b>.</p>",
			},
			{
				"label": "Default Billing Address",
				"fieldname": "default_billing_address",
				"insert_after": "default_billing_contact",
				"fieldtype": "Link",
				"options": "Address",
			},
			{
				"fieldname": "default_billing_address_html",
				"insert_after": "default_billing_address",
				"fieldtype": "HTML",
			},
			{
				"label": "Default Billing Contact",
				"fieldname": "default_billing_contact",
				"insert_after": "billing_and_shipping_defaults",
				"fieldtype": "Link",
				"options": "Contact",
			},
			{
				"label": "Default Shipping Address",
				"fieldname": "default_shipping_address",
				"insert_after": "default_shipping_contact",
				"fieldtype": "Link",
				"options": "Address",
			},
			{
				"fieldname": "default_shipping_address_html",
				"insert_after": "default_shipping_address",
				"fieldtype": "HTML",
			},
			{
				"label": "Default Shipping Contact",
				"fieldname": "default_shipping_contact",
				"insert_after": "column_break_41",
				"fieldtype": "Link",
				"options": "Contact",
			},
			{
				"label": "E Invoice Profile",
				"fieldname": "einvoice_profile",
				"insert_after": "buyer_reference",
				"fieldtype": "Select",
				"options": "\nBASIC\nEN 16931\nEXTENDED\nXRECHNUNG",
				"default": "EXTENDED",
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "column_break0",
				"fieldtype": "Link",
				"options": "Organization",
			},
		],
		"Deleted Document": [
			{
				"label": "GitHub Sync ID",
				"fieldname": "github_sync_id",
				"fieldtype": "Data",
				"unique": 1,
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
			},
			{
				"label": "Hub Sync ID",
				"fieldname": "hub_sync_id",
				"fieldtype": "Data",
				"unique": 1,
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
			},
		],
		"Delivery Note": [
			{
				"label": "Billing Contact",
				"fieldname": "billing_contact",
				"insert_after": "address_display",
				"fieldtype": "Link",
				"options": "Contact",
				"print_hide": 1,
			},
			{
				"label": "Billing Contact",
				"fieldname": "billing_contact_display",
				"insert_after": "billing_contact",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Email (Billing Contact)",
				"fieldname": "billing_contact_email",
				"insert_after": "billing_contact_mobile",
				"fieldtype": "Data",
				"options": "Email",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Mobile No (Billing Contact)",
				"fieldname": "billing_contact_mobile",
				"insert_after": "billing_contact_phone",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Phone (Billing Contact)",
				"fieldname": "billing_contact_phone",
				"insert_after": "billing_contact_display",
				"fieldtype": "Data",
				"read_only": 1,
			},
			{
				"label": "Phone (Shipping Contact)",
				"fieldname": "contact_phone",
				"insert_after": "contact_display",
				"fieldtype": "Data",
				"read_only": 1,
			},
			{
				"label": "Create Sales Invoice",
				"fieldname": "create_sales_invoice",
				"insert_after": "customer",
				"fieldtype": "Check",
				"default": "1",
				"read_only": 1,
			},
			{
				"label": "Delivery Note",
				"fieldname": "delivery_note_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Delivery Note Info Text",
				"fieldname": "delivery_note_info_text",
				"insert_after": "delivery_note_info_section",
				"fieldtype": "HTML",
				"options": "<p>Eine Lieferung bzw. ein Lieferschein kann entweder direkt oder aus einer <b><a href=\"/app/sales-order\">Bestellung</a></b> heraus erzeugt werden. Sollte er aus einer Bestellung heraus erzeugt worden sein ist diese unter Verknüpfungen verlinkt. Nur der Regionalverband kann Lieferscheine erstellen.</p>\n\n<p>Lieferscheine werden beim erstmaligen Speichern als Entwurf im System hinterlegt und können anschließend noch bearbeitet werden. Erst wenn ein Lieferschein gebucht wird ist dieser endgültig bestätigt.</p>\n\n<p>Alle verbuchten Lieferungen werden in der <b><a href=\"/app/query-report/LANDA%20Deliveries%20and%20Payments\">Kostenübersicht</a></b> aufgelistet. </p>\n\n<p>Mehr Infos zum Thema gibt es im Anleitungsvideo: <a href=\"https://youtu.be/8NG8tPfTOaU\" style=\"color: blue;\">Bestellwesen #03 Lieferung und Retoure</a> und in den <a href=\"https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF\" style=\"color: blue;\">LANDA Videotutorials - Bestellwesen</a></p>",
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "customer_name",
				"fieldtype": "Link",
				"options": "Organization",
				"fetch_from": "customer.organization",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Year of Settlement",
				"fieldname": "year_of_settlement",
				"insert_after": "posting_date",
				"fieldtype": "Int",
				"non_negative": 1,
				"reqd": 1,
			},
		],
		"Delivery Note Item": [
			{
				"label": "Cannot be Returned",
				"fieldname": "cannot_be_returned",
				"insert_after": "item_name",
				"fieldtype": "Check",
				"fetch_from": "item_code.cannot_be_returned",
				"read_only": 1,
				"in_list_view": 1,
				"columns": 1,
			},
		],
		"Item": [
			{
				"label": "Cannot be Ordered",
				"fieldname": "cannot_be_ordered",
				"insert_after": "valid_from_year",
				"fieldtype": "Check",
				"default": "0",
			},
			{
				"label": "Cannot be Returned",
				"fieldname": "cannot_be_returned",
				"insert_after": "cannot_be_ordered",
				"fieldtype": "Check",
				"default": "0",
			},
			{
				"fieldname": "column_break_54",
				"insert_after": "cannot_be_returned",
				"fieldtype": "Column Break",
			},
			{
				"label": "Company",
				"fieldname": "company",
				"insert_after": "disabled",
				"fieldtype": "Link",
				"options": "Company",
				"reqd": 1,
			},
			{
				"fieldname": "custom_section_break_4h61m",
				"insert_after": "image",
				"fieldtype": "Section Break",
			},
			{
				"label": "Hub Sync ID",
				"fieldname": "hub_sync_id",
				"fieldtype": "Data",
				"unique": 1,
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
			},
			{
				"label": "Item",
				"fieldname": "item_info_section",
				"insert_after": "hub_sync_id",
				"fieldtype": "Section Break",
			},
			{
				"label": "Item Info Text",
				"fieldname": "item_info_text",
				"insert_after": "item_info_section",
				"fieldtype": "HTML",
				"options": "<p>Im System hinterlegte Artikel können durch den Verein bestellt bzw. angefordert und durch den Regionalverband geliefert werden.</p>\n\n<p>Eine Übersicht der Artikel finden Sie <b><a href=\"/app/item\">hier</a></b>.</p>",
			},
			{
				"label": "Item Tax Template",
				"fieldname": "item_tax_template",
				"insert_after": "taxes",
				"fieldtype": "Link",
				"options": "Item Tax Template",
				"depends_on": "eval: doc.__islocal && !doc.create_variant",
				"allow_in_quick_entry": 1,
			},
			{
				"label": "LANDA",
				"fieldname": "section_break_52",
				"insert_after": "serial_no_series",
				"fieldtype": "Section Break",
			},
			{
				"label": "Valid From Year",
				"fieldname": "valid_from_year",
				"insert_after": "section_break_52",
				"length": 4,
				"fieldtype": "Int",
				"non_negative": 1,
				"in_standard_filter": 1,
				"in_preview": 1,
			},
			{
				"label": "Valid To Year",
				"fieldname": "valid_to_year",
				"insert_after": "column_break_54",
				"length": 4,
				"fieldtype": "Int",
				"default": "2100",
				"non_negative": 1,
				"in_standard_filter": 1,
				"in_preview": 1,
			},
		],
		"Item Attribute": [
			{
				"label": "Item Attribute",
				"fieldname": "item_attribute_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Item Attribute Info Text",
				"fieldname": "item_attribute_info_text",
				"insert_after": "item_attribute_info_section",
				"fieldtype": "HTML",
				"options": "<p>Ein Artikelattribut bzw. eine Artikeleigenschaft ist etwas, das mehrere Artikel vereint. Dabei handelt es sich um Angaben wie z. B. Gültigkeitsjahr oder Erlaubnisscheinart.</p>\n\n<p>Wenn ein Artikel einer Bestellung oder einem Lieferschein hinzugefügt wird, muss die entsprechende Ausprägung des Artikelattributs gewählt werden, z. B. \"Erlaubnisschein - mit Gültigkeitsjahr 2022 und Erlaubnisscheinart Salmoniden Vollzahler\". Verfügt ein Artikel über ein Gültigkeitsjahr kann dieser nur ausgewählt werden, wenn zuvor das passende Abrechnungsjahr ausgewählt wurde.</p>\n\n<p>Eine Übersicht der Artikelattribute finden Sie <b><a href=\"/app/item-attribute\">hier</a></b>.</p>",
			},
			{
				"fieldname": "section_break_3",
				"insert_after": "item_attribute_info_text",
				"fieldtype": "Section Break",
			},
		],
		"Item Price": [
			{
				"label": "Company",
				"fieldname": "company",
				"insert_after": "column_break_17",
				"fieldtype": "Link",
				"options": "Company",
			},
		],
		"Letter Head": [
			{
				"label": "Company",
				"fieldname": "custom_company",
				"fieldtype": "Link",
				"options": "Company",
			},
		],
		"Party Account": [
			{
				"label": "Debtor/Creditor Number",
				"fieldname": "debtor_creditor_number",
				"insert_after": "account",
				"fieldtype": "Data",
			},
		],
		"Payment Entry": [
			{
				"label": "Get Outstanding Invoices",
				"fieldname": "custom_get_outstanding_invoices",
				"insert_after": "get_outstanding_invoices",
				"fieldtype": "Button",
				"depends_on": "eval:doc.docstatus==0",
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "party_name",
				"fieldtype": "Link",
				"options": "Organization",
				"fetch_from": "party.organization",
				"fetch_if_empty": 1,
				"read_only_depends_on": "eval:doc.party_type=='Customer'",
			},
			{
				"label": "Payment Entry",
				"fieldname": "payment_entry_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Payment Entry Info Text",
				"fieldname": "payment_entry_info_text",
				"insert_after": "payment_entry_info_section",
				"fieldtype": "HTML",
				"options": "<p>Es gibt Zahlungseingänge und -ausgänge. Gebuchte Zahlungen werden in der <b><a href=\"/app/query-report/LANDA%20Deliveries%20and%20Payments\">Kostenübersicht</a></b> aufgelistet. Bei Zahlungseingang kann direkt aus der dazugehörigen Rechnung heraus ein Zahlungseintrag erzeugt werden.</p>\n\n<p>Eine Übersicht der Zahlungen finden Sie <b><a href=\"/app/payment-entry\">hier</a></b>. Beachten Sie nach dem Speichern auch die verlinkten Elemente unter Verknüpfungen.</p>\n\n<p>Mehr Infos zum Thema gibt es im Anleitungsvideo: <a href=\"https://youtu.be/K_dRy4jVUYo\" style=\"color: blue;\">Bestellwesen #04 Zahlung und Kostenübersicht</a> und in den <a href=\"https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF\" style=\"color: blue;\">LANDA Videotutorials - Bestellwesen</a></p>",
			},
			{
				"label": "Year of Settlement",
				"fieldname": "year_of_settlement",
				"insert_after": "posting_date",
				"fieldtype": "Int",
				"non_negative": 1,
				"reqd": 1,
			},
		],
		"Price List": [
			{
				"label": "Company",
				"fieldname": "company",
				"insert_after": "sb_1",
				"fieldtype": "Link",
				"options": "Company",
			},
		],
		"Print Settings": [
			{
				"label": "Compact Item Print",
				"fieldname": "compact_item_print",
				"insert_after": "with_letterhead",
				"fieldtype": "Check",
				"default": "1",
			},
			{
				"label": "Print taxes with zero amount",
				"fieldname": "print_taxes_with_zero_amount",
				"insert_after": "allow_print_for_cancelled",
				"fieldtype": "Check",
				"default": "0",
			},
			{
				"label": "Print UOM after Quantity",
				"fieldname": "print_uom_after_quantity",
				"insert_after": "compact_item_print",
				"fieldtype": "Check",
				"default": "0",
			},
		],
		"Project": [
			{
				"label": "GitHub Sync ID",
				"fieldname": "github_sync_id",
				"fieldtype": "Data",
				"unique": 1,
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
			},
		],
		"Purchase Invoice": [
			{
				"label": "E Invoice Import",
				"fieldname": "e_invoice_import",
				"insert_after": "bill_no",
				"fieldtype": "Link",
				"options": "E Invoice Import",
				"read_only": 1,
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "company",
				"fieldtype": "Link",
				"options": "Organization",
				"default": "LV",
				"reqd": 1,
			},
			{
				"label": "Supplier Invoice File",
				"fieldname": "supplier_invoice_file",
				"insert_after": "bill_date",
				"fieldtype": "Attach",
			},
		],
		"Sales Invoice": [
			{
				"label": "Buyer Reference",
				"fieldname": "buyer_reference",
				"insert_after": "tax_id",
				"fieldtype": "Data",
				"fetch_from": "customer.buyer_reference",
				"fetch_if_empty": 1,
			},
			{
				"label": "Phone (Billing Contact)",
				"fieldname": "contact_phone",
				"insert_after": "contact_display",
				"fieldtype": "Data",
				"read_only": 1,
			},
			{
				"fieldname": "e_invoice_validation_section",
				"insert_after": "einvoice_tab",
				"fieldtype": "Section Break",
			},
			{
				"label": "E Invoice Is Correct",
				"fieldname": "einvoice_is_correct",
				"insert_after": "e_invoice_validation_section",
				"fieldtype": "Check",
				"depends_on": "eval:!!doc.einvoice_profile",
				"read_only": 1,
				"print_hide": 1,
			},
			{
				"label": "E Invoice Profile",
				"fieldname": "einvoice_profile",
				"insert_after": "e_invoice_validation_section",
				"fieldtype": "Select",
				"options": "\nBASIC\nEN 16931\nEXTENDED\nXRECHNUNG",
				"fetch_from": "customer.einvoice_profile",
				"fetch_if_empty": 1,
				"default": "EXTENDED",
				"print_hide": 1,
			},
			{
				"label": "E Invoicing",
				"fieldname": "einvoice_tab",
				"insert_after": "terms",
				"fieldtype": "Tab Break",
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "customer_name",
				"fieldtype": "Link",
				"options": "Organization",
				"fetch_from": "customer.organization",
				"read_only": 1,
			},
			{
				"label": "Sales Invoice",
				"fieldname": "sales_invoice_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Sales Invoice Info Text",
				"fieldname": "sales_invoice_info_text",
				"insert_after": "sales_invoice_info_section",
				"fieldtype": "HTML",
				"options": "<p>Eine Rechnung wird in der Regel automatisch aus der Lieferung bzw. dem Lieferschein erzeugt und gebucht. Rechnungen können an den Verein gesendet werden und dienen der Buchhaltung. Bei Zahlungseingang kann direkt aus der Rechnung heraus ein Zahlungseintrag erzeugt werden.</p>\n\n<p>Eine Übersicht der Rechnungen finden Sie <b><a href=\"/app/sales-invoice\">hier</a></b>. Beachten Sie nach dem Speichern auch die verlinkten Elemente unter Verknüpfungen.</p>",
			},
			{
				"label": "Shipping Contact",
				"fieldname": "shipping_contact",
				"insert_after": "shipping_address",
				"fieldtype": "Link",
				"options": "Contact",
				"print_hide": 1,
			},
			{
				"label": "Shipping Contact",
				"fieldname": "shipping_contact_display",
				"insert_after": "shipping_contact",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Email (Shipping Contact)",
				"fieldname": "shipping_contact_email",
				"insert_after": "shipping_contact_mobile",
				"fieldtype": "Data",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Mobile No (Shipping Contact)",
				"fieldname": "shipping_contact_mobile",
				"insert_after": "shipping_contact_phone",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Phone (Shipping Contact)",
				"fieldname": "shipping_contact_phone",
				"insert_after": "shipping_contact_display",
				"fieldtype": "Data",
				"read_only": 1,
			},
			{
				"label": "Validation Errors",
				"fieldname": "validation_errors",
				"insert_after": "einvoice_is_correct",
				"fieldtype": "Text",
				"depends_on": "eval:doc.einvoice_profile && !doc.einvoice_is_correct",
				"read_only": 1,
				"print_hide": 1,
			},
			{
				"label": "Validation Warnings",
				"fieldname": "validation_warnings",
				"insert_after": "validation_errors",
				"fieldtype": "Text",
				"depends_on": "eval:doc.einvoice_profile && doc.validation_warnings",
				"read_only": 1,
				"print_hide": 1,
				"no_copy": 1,
			},
			{
				"label": "Year of Settlement",
				"fieldname": "year_of_settlement",
				"insert_after": "posting_date",
				"fieldtype": "Int",
				"non_negative": 1,
				"reqd": 1,
			},
		],
		"Sales Order": [
			{
				"label": "Buyer Reference",
				"fieldname": "buyer_reference",
				"insert_after": "tax_id",
				"fieldtype": "Data",
				"fetch_from": "customer.buyer_reference",
				"fetch_if_empty": 1,
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "customer_name",
				"fieldtype": "Link",
				"options": "Organization",
				"fetch_from": "customer.organization",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"label": "Sales Order",
				"fieldname": "sales_order_info_section",
				"fieldtype": "Section Break",
			},
			{
				"label": "Sales Order Info Text",
				"fieldname": "sales_order_info_text",
				"insert_after": "sales_order_info_section",
				"fieldtype": "HTML",
				"options": "<p>Eine Bestellung ist eine Bedarfsanmeldung vom Verein (Kunde) an den Regionalverband (Unternehmen). Der Regionalverband erstellt daraus anschließend eine Lieferung, kann dabei aber die bestellten Artikel noch beliebig anpassen.</p>\n\n<p>Wenn Sie eine Bestellung erstmalig speichern wird diese zunächst als Entwurf im System hinterlegt und kann anschließend noch bearbeitet werden. Erst wenn Sie eine Bestellung buchen wird diese festgeschrieben und vom Regionalverband bearbeitet.</p>\n\n<p>Eine Übersicht der Bestellungen finden Sie <b><a href=\"/app/sales-order\">hier</a></b>. Beachten Sie nach dem Speichern auch die verlinkten Elemente unter Verknüpfungen.</p>\n\n<p>Mehr Infos zum Thema gibt es im Anleitungsvideo: <a href=\"https://youtu.be/uA7ifVwLk-M\" style=\"color: blue;\">Bestellwesen #02 Bestellungen</a> und in den <a href=\"https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF\" style=\"color: blue;\">LANDA Videotutorials - Bestellwesen</a></p>",
			},
			{
				"label": "Shipping Contact",
				"fieldname": "shipping_contact",
				"insert_after": "shipping_address",
				"fieldtype": "Link",
				"options": "Contact",
				"read_only_depends_on": 'eval: !frappe.user.has_role("LANDA Regional Organization Management")',
				"print_hide": 1,
			},
			{
				"label": "Shipping Contact",
				"fieldname": "shipping_contact_display",
				"insert_after": "shipping_contact",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Email (Shipping Contact)",
				"fieldname": "shipping_contact_email",
				"insert_after": "shipping_contact_mobile",
				"fieldtype": "Data",
				"options": "Email",
				"read_only": 1,
				"hidden": 1,
				"print_hide": 1,
			},
			{
				"label": "Mobile No (Shipping Contact)",
				"fieldname": "shipping_contact_mobile",
				"insert_after": "shipping_contact_phone",
				"fieldtype": "Small Text",
				"read_only": 1,
			},
			{
				"label": "Phone (Shipping Contact)",
				"fieldname": "shipping_contact_phone",
				"insert_after": "shipping_contact_display",
				"fieldtype": "Data",
				"read_only": 1,
			},
			{
				"label": "Year of Settlement",
				"fieldname": "year_of_settlement",
				"insert_after": "transaction_date",
				"fieldtype": "Int",
				"depends_on": "eval: doc.customer",
				"non_negative": 1,
				"reqd": 1,
			},
		],
		"Sales Order Item": [
			{
				"label": "Cannot be Returned",
				"fieldname": "cannot_be_returned",
				"insert_after": "customer_item_code",
				"fieldtype": "Check",
				"fetch_from": "item_code.cannot_be_returned",
				"read_only": 1,
				"in_list_view": 1,
				"columns": 1,
			},
		],
		"Supplier": [
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "supplier_name",
				"fieldtype": "Link",
				"options": "Organization",
				"default": "LV",
				"reqd": 1,
			},
		],
		"Tag": [
			{
				"label": "Organizations",
				"fieldname": "organizations",
				"insert_after": "description",
				"fieldtype": "Table",
				"options": "Tag Organization",
			},
		],
		"Task": [
			{
				"label": "GitHub Sync ID",
				"fieldname": "github_sync_id",
				"fieldtype": "Data",
				"unique": 1,
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
			},
		],
		"User": [
			{
				"label": "LANDA Member",
				"fieldname": "landa_member",
				"insert_after": "username",
				"fieldtype": "Link",
				"options": "LANDA Member",
				"in_standard_filter": 1,
				"allow_in_quick_entry": 1,
			},
			{
				"label": "Organization",
				"fieldname": "organization",
				"insert_after": "landa_member",
				"fieldtype": "Link",
				"options": "Organization",
				"fetch_from": "landa_member.organization",
				"read_only": 1,
				"in_standard_filter": 1,
				"allow_in_quick_entry": 1,
			},
		],
	}
