def get_doc_perms():
	return {
		"Account": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "Accounts User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Auditor", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Employee Self Service", "permlevel": 0, "select": 1, "export": 1},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "select": 1, "read": 1},
			{"role": "Purchase User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Sales User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
		],
		"Address": [
			{
				"role": "LANDA Local Group Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Company": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Accounts User", "permlevel": 0, "read": 1, "print": 1, "email": 1},
			{"role": "Employee", "permlevel": 0, "read": 1},
			{"role": "Employee Self Service", "permlevel": 0, "select": 1, "export": 1},
			{"role": "LANDA Member", "permlevel": 0, "select": 1},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Projects User", "permlevel": 0, "read": 1},
			{"role": "Purchase User", "permlevel": 0, "read": 1},
			{"role": "Sales User", "permlevel": 0, "read": 1},
			{"role": "Stock User", "permlevel": 0, "read": 1},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
		],
		"Contact": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Accounts User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "All", "permlevel": 1, "read": 1, "report": 1},
			{
				"role": "LANDA Local Group Management",
				"permlevel": 0,
				"select": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"select": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"select": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "Maintenance Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Maintenance User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Purchase Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Purchase Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Purchase User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Sales Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Sales Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Sales User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Currency": [
			{"role": "Accounts User", "permlevel": 0, "read": 1},
			{"role": "Employee Self Service", "permlevel": 0, "select": 1, "export": 1},
			{"role": "LANDA Member", "permlevel": 0, "read": 1},
			{"role": "Purchase User", "permlevel": 0, "read": 1},
			{"role": "Sales User", "permlevel": 0, "read": 1},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Customer": [
			{"role": "Accounts Manager", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Accounts User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "LANDA Local Group Management", "permlevel": 0, "read": 1},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "read": 1},
			{"role": "Sales Manager", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{
				"role": "Sales Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Sales Master Manager", "permlevel": 1, "read": 1, "write": 1},
			{
				"role": "Sales User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "Sales User", "permlevel": 1, "read": 1},
			{"role": "Stock Manager", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Stock User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
		],
		"Customer Group": [
			{
				"role": "Customer",
				"permlevel": 0,
				"select": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "read": 1},
			{"role": "Sales Manager", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Sales Manager", "permlevel": 1, "read": 1},
			{
				"role": "Sales Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Sales Master Manager", "permlevel": 1, "read": 1, "write": 1},
			{"role": "Sales User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Sales User", "permlevel": 1, "read": 1},
		],
		"Data Import": [
			{
				"role": "LANDA Catch Log User",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Local Group Management",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Local Water Body Management",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA Regional Water Body Management",
				"permlevel": 0,
				"if_owner": 1,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Delivery Note": [
			{"role": "Accounts User", "permlevel": 0, "read": 1, "report": 1},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"read": 1,
				"print": 1,
				"report": 1,
				"export": 1,
			},
			{
				"role": "Sales User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "Stock Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "Stock Manager", "permlevel": 1, "read": 1, "write": 1},
			{
				"role": "Stock User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
		],
		"Item Tax Template": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "Accounts User",
				"permlevel": 0,
				"read": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "select": 1, "read": 1},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Note": [
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
			},
		],
		"Payment Entry": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "Accounts User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "read": 1, "report": 1},
		],
		"Sales Invoice": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "Accounts Manager", "permlevel": 1, "read": 1, "write": 1},
			{
				"role": "Accounts User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"submit": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "All", "permlevel": 1, "read": 1},
			{"role": "Employee Self Service", "permlevel": 0, "select": 1, "export": 1},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"read": 1,
				"print": 1,
				"report": 1,
				"export": 1,
			},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"delete": 1,
				"cancel": 1,
				"print": 1,
			},
		],
		"Sales Order": [
			{"role": "Accounts User", "permlevel": 0, "read": 1, "print": 1, "email": 1},
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"print": 1,
				"report": 1,
				"export": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 1, "read": 1, "export": 1},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"report": 1,
				"export": 1,
			},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 1,
				"read": 1,
				"write": 1,
				"export": 1,
			},
			{
				"role": "Maintenance User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{
				"role": "Sales Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Sales Manager", "permlevel": 1, "read": 1, "write": 1},
			{
				"role": "Sales User",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"submit": 1,
				"cancel": 1,
				"amend": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "Stock User", "permlevel": 0, "read": 1, "report": 1},
		],
		"Sales Taxes and Charges Template": [
			{
				"role": "Accounts Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "select": 1},
			{
				"role": "Sales Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"share": 1,
			},
			{"role": "Sales User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
		],
		"Tag": [
			{
				"role": "All",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{
				"role": "LANDA State Organization Employee",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
			},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
		],
		"Territory": [
			{
				"role": "Customer",
				"permlevel": 0,
				"select": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "LANDA Local Organization Management", "permlevel": 0, "read": 1, "export": 1},
			{"role": "Maintenance User", "permlevel": 0, "read": 1},
			{"role": "Sales Manager", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{
				"role": "Sales Master Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "Sales User", "permlevel": 0, "read": 1, "print": 1, "email": 1, "report": 1},
			{"role": "Stock User", "permlevel": 0, "read": 1},
		],
		"User": [
			{
				"role": "LANDA Local Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
			},
			{"role": "LANDA Member", "permlevel": 0, "select": 1},
			{
				"role": "LANDA Regional Organization Management",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
			},
			{
				"role": "LANDA State Organization Employee",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
			},
			{
				"role": "System Manager",
				"permlevel": 0,
				"read": 1,
				"write": 1,
				"create": 1,
				"delete": 1,
				"print": 1,
				"email": 1,
				"report": 1,
				"import": 1,
				"export": 1,
				"share": 1,
			},
			{"role": "System Manager", "permlevel": 1, "read": 1, "write": 1},
		],
	}
