def get_property_setters():
	return {
		"Address": [
			(
				None,
				"field_order",
				'["address_details", "address_info_text", "address_2", "column_break_2", "address_title", "address_type", "address_line1", "address_line2", "city", "county", "state", "country", "pincode", "column_break0", "email_id", "phone", "fax", "tax_category", "is_primary_address", "is_shipping_address", "disabled", "linked_with", "is_your_company_address", "links", "organization", "customer", "landa_member"]',
			),
			(None, "search_fields", "pincode, city, address_line1"),
			("address_details", "label", "Address"),
			(
				"address_info_text",
				"options",
				'<p>Infos zum Thema Mitgliederverwaltung gibt es in den <a href="https://youtube.com/playlist?list=PLCG04RYNrML993pHOo16el5DGrKN5kCzh" target="_blank">LANDA Videotutorials - Vereinsverwaltung / Mitgliederverwaltung</a></p>',
			),
			("address_type", "default", "Personal"),
			("city", "in_global_search", "0"),
			("country", "in_global_search", "0"),
			("county", "hidden", "1"),
			("email_id", "hidden", "1"),
			("fax", "hidden", "1"),
			("is_primary_address", "hidden", "1"),
			("is_shipping_address", "hidden", "1"),
			("links", "reqd", "1"),
			("organization", "hidden", "0"),
			("phone", "hidden", "1"),
			("pincode", "reqd", "1"),
			("state", "hidden", "1"),
		],
		"Company": [
			("budget_detail", "hidden", "1"),
			("company_info", "collapsible", "0"),
			("fixed_asset_depreciation_settings", "hidden", "1"),
			("registration_info", "hidden", "1"),
			("sales_settings", "hidden", "1"),
		],
		"Contact": [
			(
				None,
				"field_order",
				'["contact_section", "contact_info", "contacts_2", "column_break_2", "first_name", "middle_name", "last_name", "email_id", "user", "address", "sync_with_google_contacts", "cb00", "status", "salutation", "designation", "gender", "phone", "mobile_no", "company_name", "image", "sb_00", "google_contacts", "google_contacts_id", "cb_00", "pulled_from_google_contacts", "sb_01", "email_ids", "phone_nos", "contact_details", "links", "organization", "landa_member", "customer", "is_primary_contact", "is_billing_contact", "more_info", "department", "unsubscribed"]',
			),
			("address", "hidden", "1"),
			("company_name", "hidden", "1"),
			(
				"contact_info",
				"options",
				'<p>Infos zum Thema Mitgliederverwaltung gibt es in den <a href="https://youtube.com/playlist?list=PLCG04RYNrML993pHOo16el5DGrKN5kCzh" target="_blank">LANDA Videotutorials - Vereinsverwaltung / Mitgliederverwaltung</a></p>',
			),
			("contact_section", "label", "Contact"),
			("department", "hidden", "1"),
			("designation", "hidden", "1"),
			("email_id", "in_global_search", "0"),
			("first_name", "in_global_search", "0"),
			("is_primary_contact", "hidden", "1"),
			("links", "reqd", "1"),
			("more_info", "hidden", "1"),
			("status", "hidden", "1"),
			("sync_with_google_contacts", "hidden", "1"),
			("unsubscribed", "hidden", "1"),
			("user", "hidden", "1"),
			("user", "read_only", "1"),
			("user", "in_global_search", "0"),
		],
		"Customer": [
			(
				None,
				"field_order",
				'["customer_info_section", "cutomer_info_text", "basic_info", "naming_series", "salutation", "customer_name", "customer_type", "customer_group", "column_break0", "organization", "territory", "gender", "lead_name", "opportunity_name", "account_manager", "image", "defaults_tab", "default_price_list", "default_bank_account", "column_break_14", "default_currency", "internal_customer_section", "is_internal_customer", "represents_company", "column_break_70", "companies", "more_info", "market_segment", "industry", "customer_pos_id", "website", "language", "buyer_reference", "einvoice_profile", "column_break_45", "customer_details", "dashboard_tab", "contact_and_address_tab", "address_contacts", "address_html", "column_break1", "contact_html", "billing_and_shipping_defaults", "default_billing_contact", "default_billing_address", "default_billing_address_html", "column_break_41", "default_shipping_contact", "default_shipping_address", "default_shipping_address_html", "primary_address_and_contact_detail", "customer_primary_contact", "mobile_no", "email_id", "column_break_26", "customer_primary_address", "primary_address", "tax_tab", "taxation_section", "tax_id", "column_break_21", "tax_category", "tax_withholding_category", "accounting_tab", "credit_limit_section", "payment_terms", "credit_limits", "default_receivable_accounts", "accounts", "loyalty_points_tab", "loyalty_program", "column_break_54", "loyalty_program_tier", "sales_team_tab", "sales_team", "sales_team_section", "default_sales_partner", "column_break_66", "default_commission_rate", "settings_tab", "so_required", "dn_required", "column_break_53", "is_frozen", "disabled"]',
			),
			("account_manager", "hidden", "1"),
			("address_contacts", "depends_on", "eval:!doc.__islocal"),
			("column_break_38", "hidden", "1"),
			("credit_limit_section", "hidden", "1"),
			("customer_group", "default", "Non Profit"),
			("customer_group", "hidden", "1"),
			("customer_group", "in_list_view", "0"),
			("customer_group", "in_standard_filter", "0"),
			("customer_type", "read_only", "1"),
			("default_bank_account", "hidden", "1"),
			("default_receivable_accounts", "hidden", "1"),
			("industry", "hidden", "1"),
			("internal_customer_section", "hidden", "1"),
			("lead_name", "hidden", "1"),
			("loyalty_points_tab", "hidden", "1"),
			("market_segment", "hidden", "1"),
			("naming_series", "hidden", "1"),
			("naming_series", "options", "CUST-.YYYY.-"),
			("naming_series", "reqd", "0"),
			("opportunity_name", "hidden", "1"),
			("organization", "in_standard_filter", "1"),
			("pan", "hidden", "1"),
			("primary_address_and_contact_detail", "hidden", "1"),
			("sales_team_section", "hidden", "1"),
			("sales_team_section_break", "hidden", "1"),
			("sales_team_tab", "hidden", "1"),
			("tax_category", "read_only", "1"),
			("tax_withholding_category", "hidden", "1"),
			("territory", "default", "All Territories"),
			("territory", "hidden", "1"),
			("territory", "in_list_view", "0"),
			("territory", "in_standard_filter", "0"),
			("website", "hidden", "1"),
		],
		"Delivery Note": [
			(None, "default_print_format", "DN DIN Addressfield"),
			(
				None,
				"field_order",
				'["delivery_note_info_text", "delivery_note_info_section", "title", "naming_series", "customer", "create_sales_invoice", "tax_id", "customer_name", "organization", "column_break1", "posting_date", "year_of_settlement", "posting_time", "set_posting_time", "column_break_10", "company", "amended_from", "is_return", "issue_credit_note", "return_against", "accounting_dimensions_section", "cost_center", "column_break_18", "project", "dimension_col_break", "custom_dimensions_section", "currency_and_price_list", "currency", "conversion_rate", "col_break23", "selling_price_list", "price_list_currency", "plc_conversion_rate", "ignore_pricing_rule", "items_section", "scan_barcode", "pick_list", "col_break_warehouse", "set_warehouse", "set_target_warehouse", "section_break_30", "items", "section_break_31", "total_qty", "total_net_weight", "column_break_35", "base_total", "base_net_total", "column_break_33", "total", "net_total", "taxes_section", "tax_category", "taxes_and_charges", "column_break_43", "shipping_rule", "column_break_39", "incoterm", "named_place", "section_break_41", "taxes", "section_break_44", "base_total_taxes_and_charges", "column_break_47", "total_taxes_and_charges", "totals", "base_grand_total", "base_rounding_adjustment", "base_rounded_total", "base_in_words", "column_break3", "grand_total", "rounding_adjustment", "rounded_total", "in_words", "disable_rounded_total", "section_break_49", "apply_discount_on", "base_discount_amount", "column_break_51", "additional_discount_percentage", "discount_amount", "sec_tax_breakup", "other_charges_calculation", "packing_list", "packed_items", "product_bundle_help", "pricing_rule_details", "pricing_rules", "address_and_contact_tab", "contact_info", "customer_address", "address_display", "billing_contact", "billing_contact_display", "billing_contact_phone", "billing_contact_mobile", "billing_contact_email", "col_break21", "contact_person", "contact_display", "contact_phone", "contact_mobile", "contact_email", "shipping_address_section", "shipping_address_name", "shipping_address", "column_break_95", "dispatch_address_name", "dispatch_address", "company_address_section", "company_address", "column_break_101", "company_contact_person", "company_address_display", "terms_tab", "tc_name", "terms", "more_info_tab", "section_break_83", "per_billed", "status", "column_break_112", "per_installed", "installation_status", "column_break_89", "per_returned", "transporter_info", "transporter", "driver", "lr_no", "vehicle_no", "col_break34", "transporter_name", "driver_name", "lr_date", "customer_po_details", "po_no", "column_break_17", "po_date", "sales_team_section_break", "sales_partner", "amount_eligible_for_commission", "column_break7", "commission_rate", "total_commission", "section_break1", "sales_team", "subscription_section", "auto_repeat", "printing_details", "letter_head", "print_without_amount", "group_same_items", "column_break_88", "select_print_heading", "language", "more_info", "is_internal_customer", "represents_company", "inter_company_reference", "customer_group", "territory", "source", "campaign", "column_break5", "excise_page", "instructions", "connections_tab"]',
			),
			(None, "naming_rule", "By script"),
			("accounting_dimensions_section", "hidden", "1"),
			("billing_contact", "fetch_from", "customer.default_billing_contact"),
			("billing_contact", "fetch_if_empty", "1"),
			("company_address", "hidden", "1"),
			("contact_display", "label", "Shipping Contact"),
			("contact_email", "label", "Email (Shipping Contact)"),
			("contact_mobile", "label", "Mobile No (Shipping Contact)"),
			("contact_person", "fetch_from", "customer.default_shipping_contact"),
			("contact_person", "fetch_if_empty", "1"),
			("contact_person", "label", "Shipping Contact"),
			("conversion_rate", "default", "1"),
			("conversion_rate", "hidden", "1"),
			("currency", "default", "EUR"),
			("currency", "read_only", "1"),
			("currency_and_price_list", "collapsible", "0"),
			("customer_address", "fetch_from", "customer.default_billing_address"),
			("customer_address", "fetch_if_empty", "1"),
			("customer_address", "label", "Billing Address"),
			("customer_po_details", "hidden", "1"),
			(
				"delivery_note_info_text",
				"options",
				'<p>Infos zum Thema Bestellwesen in den <a href="https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF" target="_blank">LANDA Videotutorials - Bestellwesen</a></p>',
			),
			("dispatch_address_name", "hidden", "1"),
			("ignore_pricing_rule", "hidden", "1"),
			("more_info", "hidden", "1"),
			("naming_series", "options", "MAT-DN-.YYYY.-\nMAT-DN-RET-.YYYY.-"),
			("per_billed", "in_list_view", "1"),
			("per_installed", "in_list_view", "0"),
			("plc_conversion_rate", "default", "1"),
			("plc_conversion_rate", "hidden", "1"),
			("price_list_currency", "default", "EUR"),
			("price_list_currency", "hidden", "1"),
			("printing_details", "hidden", "1"),
			("sales_team_section_break", "hidden", "1"),
			("sec_warehouse", "hidden", "1"),
			("section_break_49", "hidden", "1"),
			("section_break1", "hidden", "1"),
			("shipping_address_name", "fetch_from", "customer.default_shipping_address"),
			("shipping_address_name", "fetch_if_empty", "1"),
			("subscription_section", "hidden", "1"),
			("tax_id", "hidden", "0"),
			("tax_id", "print_hide", "0"),
			("taxes_section", "hidden", "1"),
			("terms_section_break", "hidden", "1"),
			("transporter_info", "hidden", "1"),
			("year_of_settlement", "in_standard_filter", "1"),
		],
		"Delivery Note Item": [
			("amount", "columns", "1"),
			("batch_no", "in_list_view", "0"),
			("item_code", "columns", "4"),
			("qty", "columns", "1"),
			("rate", "columns", "1"),
			("serial_no", "columns", "2"),
			("uom", "columns", "1"),
			("uom", "in_list_view", "0"),
			("warehouse", "in_list_view", "0"),
		],
		"Item": [
			(
				None,
				"field_order",
				'["details", "item_info_text", "item_info_section", "naming_series", "item_code", "item_name", "item_group", "stock_uom", "column_break0", "disabled", "company", "allow_alternative_item", "is_stock_item", "has_variants", "include_item_in_manufacturing", "opening_stock", "valuation_rate", "standard_rate", "is_fixed_asset", "auto_create_assets", "is_grouped_asset", "asset_category", "asset_naming_series", "over_delivery_receipt_allowance", "over_billing_allowance", "image", "custom_section_break_4h61m", "valid_from_year", "cannot_be_returned", "cannot_be_ordered", "column_break_54", "valid_to_year", "section_break_11", "description", "brand", "unit_of_measure_conversion", "uoms", "dashboard_tab", "inventory_section", "inventory_settings_section", "shelf_life_in_days", "end_of_life", "default_material_request_type", "valuation_method", "column_break1", "warranty_period", "weight_per_unit", "weight_uom", "allow_negative_stock", "sb_barcodes", "barcodes", "reorder_section", "reorder_levels", "serial_nos_and_batches", "has_batch_no", "create_new_batch", "batch_number_series", "has_expiry_date", "retain_sample", "sample_quantity", "column_break_37", "has_serial_no", "serial_no_series", "variants_section", "variant_of", "variant_based_on", "attributes", "accounting", "deferred_accounting_section", "enable_deferred_expense", "no_of_months_exp", "column_break_9s9o", "enable_deferred_revenue", "no_of_months", "section_break_avcp", "item_defaults", "purchasing_tab", "purchase_uom", "min_order_qty", "safety_stock", "is_purchase_item", "purchase_details_cb", "lead_time_days", "last_purchase_rate", "is_customer_provided_item", "customer", "supplier_details", "delivered_by_supplier", "column_break2", "supplier_items", "foreign_trade_details", "country_of_origin", "column_break_59", "customs_tariff_number", "sales_details", "sales_uom", "grant_commission", "is_sales_item", "column_break3", "max_discount", "customer_details", "customer_items", "item_tax_section_break", "taxes", "item_tax_template", "quality_tab", "inspection_required_before_purchase", "quality_inspection_template", "inspection_required_before_delivery", "manufacturing", "is_sub_contracted_item", "default_bom", "column_break_74", "customer_code", "default_item_manufacturer", "default_manufacturer_part_no", "published_in_website", "total_projected_qty"]',
			),
			(None, "search_fields", "item_name,description,item_group,customer_code,cannot_be_returned"),
			("accounting", "hidden", "1"),
			("allow_alternative_item", "hidden", "1"),
			("barcodes", "hidden", "0"),
			("customer_details", "hidden", "1"),
			("defaults", "hidden", "1"),
			("deferred_expense_section", "hidden", "1"),
			("deferred_revenue", "hidden", "1"),
			("foreign_trade_details", "hidden", "1"),
			("hub_publishing_sb", "hidden", "1"),
			("include_item_in_manufacturing", "default", "0"),
			("include_item_in_manufacturing", "hidden", "1"),
			("inspection_criteria", "hidden", "1"),
			("inventory_section", "hidden", "1"),
			("is_fixed_asset", "hidden", "1"),
			("is_item_from_hub", "hidden", "1"),
			("is_stock_item", "bold", "0"),
			("is_stock_item", "default", "0"),
			("is_stock_item", "hidden", "1"),
			("item_code", "hidden", "1"),
			("item_code", "reqd", "0"),
			("item_defaults", "hidden", "1"),
			("item_group", "default", "All Item Groups"),
			("manufacturing", "hidden", "1"),
			("naming_series", "default", "STO-ITEM-.YYYY.-"),
			("naming_series", "hidden", "1"),
			("naming_series", "options", "STO-ITEM-.YYYY.-"),
			("naming_series", "read_only", "1"),
			("naming_series", "reqd", "1"),
			("opening_stock", "hidden", "1"),
			("over_billing_allowance", "hidden", "1"),
			("over_delivery_receipt_allowance", "hidden", "1"),
			("purchase_details", "hidden", "1"),
			("purchasing_tab", "hidden", "1"),
			("quality_tab", "hidden", "1"),
			("reorder_section", "hidden", "1"),
			("sales_details", "hidden", "1"),
			("sb_barcodes", "hidden", "1"),
			("supplier_details", "hidden", "1"),
			("website_section", "hidden", "1"),
		],
		"Item Barcode": [
			("barcode", "hidden", "0"),
		],
		"Item Price": [
			("batch_no", "hidden", "1"),
			("batch_no", "read_only", "1"),
			("brand", "hidden", "1"),
			("brand", "in_list_view", "0"),
			("customer", "hidden", "1"),
			("customer", "read_only", "1"),
			("lead_time_days", "hidden", "1"),
			("lead_time_days", "read_only", "1"),
			("packing_unit", "hidden", "1"),
			("packing_unit", "read_only", "1"),
			("supplier", "hidden", "1"),
			("supplier", "read_only", "1"),
			("uom", "read_only", "1"),
			("uom", "default", "Anzahl"),
		],
		"Letter Head": [
			(
				None,
				"field_order",
				'["custom_company", "letter_head_name", "source", "footer_source", "column_break_3", "disabled", "is_default", "letter_head_image_section", "image", "image_height", "image_width", "align", "header_section", "content", "footer_section", "footer", "footer_image_section", "footer_image", "footer_image_height", "footer_image_width", "footer_align", "scripts_section", "header_script", "footer_script", "instructions"]',
			),
		],
		"Packed Item": [
			("rate", "read_only", "1"),
		],
		"Payment Entry": [
			(None, "default_print_format", "Zahlungsbeleg"),
			(
				None,
				"field_order",
				'["payment_entry_info_section", "payment_entry_info_text", "type_of_payment", "naming_series", "payment_type", "payment_order_status", "column_break_5", "posting_date", "year_of_settlement", "company", "mode_of_payment", "party_section", "party_type", "party", "party_name", "organization", "column_break_11", "bank_account", "party_bank_account", "contact_person", "contact_email", "payment_accounts_section", "party_balance", "paid_from", "paid_from_account_type", "paid_from_account_currency", "paid_from_account_balance", "column_break_18", "paid_to", "paid_to_account_type", "paid_to_account_currency", "paid_to_account_balance", "payment_amounts_section", "paid_amount", "paid_amount_after_tax", "source_exchange_rate", "base_paid_amount", "base_paid_amount_after_tax", "column_break_21", "received_amount", "received_amount_after_tax", "target_exchange_rate", "base_received_amount", "base_received_amount_after_tax", "section_break_14", "get_outstanding_invoices", null, "get_outstanding_orders", "references", "section_break_34", "total_allocated_amount", "base_total_allocated_amount", "set_exchange_gain_loss", "column_break_36", "unallocated_amount", "difference_amount", "write_off_difference_amount", "taxes_and_charges_section", "purchase_taxes_and_charges_template", "sales_taxes_and_charges_template", "column_break_55", "apply_tax_withholding_amount", "tax_withholding_category", "section_break_56", "taxes", "section_break_60", "base_total_taxes_and_charges", "column_break_61", "total_taxes_and_charges", "deductions_or_loss_section", "deductions", "transaction_references", "reference_no", "column_break_23", "reference_date", "clearance_date", "accounting_dimensions_section", "project", "dimension_col_break", "cost_center", "section_break_12", "status", "custom_remarks", "remarks", "column_break_16", "letter_head", "print_heading", "bank", "bank_account_no", "payment_order", "subscription_section", "auto_repeat", "amended_from", "title"]',
			),
			(None, "naming_rule", "By script"),
			("accounting_dimensions_section", "hidden", "1"),
			("bank_account", "hidden", "1"),
			("base_total_allocated_amount", "hidden", "1"),
			("deductions_or_loss_section", "hidden", "1"),
			("get_outstanding_invoices", "hidden", "1"),
			("get_outstanding_orders", "hidden", "1"),
			("mode_of_payment", "default", "Banküberweisung"),
			("mode_of_payment", "reqd", "1"),
			("naming_series", "options", "ACC-PAY-.YYYY.-"),
			("party_bank_account", "hidden", "1"),
			("party_type", "default", "Customer"),
			("payment_accounts_section", "hidden", "1"),
			("payment_type", "bold", "0"),
			("payment_type", "in_list_view", "0"),
			("payment_type", "in_standard_filter", "0"),
			("print_heading", "hidden", "1"),
			("received_amount", "in_list_view", "1"),
			("reference_date", "default", "Today"),
			("reference_date", "hidden", "1"),
			("reference_no", "default", "-"),
			("reference_no", "hidden", "1"),
			("section_break_34", "hidden", "1"),
			("section_break_56", "hidden", "1"),
			("section_break_60", "hidden", "1"),
			("taxes_and_charges_section", "hidden", "1"),
			("year_of_settlement", "in_standard_filter", "1"),
		],
		"Purchase Invoice": [
			(
				None,
				"field_order",
				'["title", "naming_series", "supplier", "supplier_name", "tax_id", "company", null, "column_break_6", "posting_date", "posting_time", "set_posting_time", "due_date", "column_break1", "is_paid", "is_return", "return_against", "update_outstanding_for_self", "update_billed_amount_in_purchase_order", "update_billed_amount_in_purchase_receipt", "apply_tds", "tax_withholding_category", "amended_from", "supplier_invoice_details", "bill_no", "e_invoice_import", "column_break_15", "bill_date", "accounting_dimensions_section", "cost_center", "dimension_col_break", "project", "currency_and_price_list", "currency", "conversion_rate", "use_transaction_date_exchange_rate", "column_break2", "buying_price_list", "price_list_currency", "plc_conversion_rate", "ignore_pricing_rule", "sec_warehouse", "scan_barcode", "col_break_warehouse", "update_stock", "set_warehouse", "set_from_warehouse", "is_subcontracted", "rejected_warehouse", "supplier_warehouse", "items_section", "items", "section_break_26", "total_qty", "total_net_weight", "column_break_50", "base_total", "base_net_total", "column_break_28", "total", "net_total", "tax_withholding_net_total", "base_tax_withholding_net_total", "taxes_section", "tax_category", "taxes_and_charges", "column_break_58", "shipping_rule", "column_break_49", "incoterm", "named_place", "section_break_51", "taxes", "totals", "base_taxes_and_charges_added", "base_taxes_and_charges_deducted", "base_total_taxes_and_charges", "column_break_40", "taxes_and_charges_added", "taxes_and_charges_deducted", "total_taxes_and_charges", "section_break_49", "base_grand_total", "base_rounding_adjustment", "base_rounded_total", "base_in_words", "column_break8", "grand_total", "rounding_adjustment", "use_company_roundoff_cost_center", "rounded_total", "in_words", "total_advance", "outstanding_amount", "disable_rounded_total", "section_break_44", "apply_discount_on", "base_discount_amount", "column_break_46", "additional_discount_percentage", "discount_amount", "tax_withheld_vouchers_section", "tax_withheld_vouchers", "sec_tax_breakup", "other_charges_calculation", "pricing_rule_details", "pricing_rules", "raw_materials_supplied", "supplied_items", "payments_tab", "payments_section", "mode_of_payment", "base_paid_amount", "clearance_date", "col_br_payments", "cash_bank_account", "paid_amount", "advances_section", "allocate_advances_automatically", "only_include_allocated_payments", "get_advances", "advances", "advance_tax", "write_off", "write_off_amount", "base_write_off_amount", "column_break_61", "write_off_account", "write_off_cost_center", "address_and_contact_tab", "section_addresses", "supplier_address", "address_display", "col_break_address", "contact_person", "contact_display", "contact_mobile", "contact_email", "company_shipping_address_section", "shipping_address", "column_break_126", "shipping_address_display", "company_billing_address_section", "billing_address", "column_break_130", "billing_address_display", "terms_tab", "payment_schedule_section", "payment_terms_template", "ignore_default_payment_terms_template", "payment_schedule", "terms_section_break", "tc_name", "terms", "more_info_tab", "status_section", "status", "column_break_177", "per_received", "accounting_details_section", "credit_to", "party_account_currency", "is_opening", "against_expense_account", "column_break_63", "unrealized_profit_loss_account", "subscription_section", "auto_repeat", "update_auto_repeat_reference", "column_break_114", "from_date", "to_date", "printing_settings", "letter_head", "group_same_items", "column_break_112", "select_print_heading", "language", "sb_14", "on_hold", "release_date", "cb_17", "hold_comment", "additional_info_section", "is_internal_supplier", "represents_company", "column_break_147", "inter_company_invoice_reference", "is_old_subcontracting_flow", "remarks", "connections_tab"]',
			),
			("additional_discount_account", "hidden", "1"),
			("additional_discount_account", "mandatory_depends_on", ""),
			("apply_tds", "hidden", "1"),
			("base_rounded_total", "hidden", "0"),
			("base_rounded_total", "print_hide", "1"),
			("cost_center", "hidden", "1"),
			("disable_rounded_total", "default", "1"),
			("disable_rounded_total", "hidden", "1"),
			("due_date", "print_hide", "0"),
			("group_same_items", "hidden", "1"),
			("in_words", "hidden", "1"),
			("in_words", "print_hide", "0"),
			("incoterm", "hidden", "1"),
			("is_internal_supplier", "hidden", "1"),
			("is_opening", "hidden", "1"),
			("is_subcontracted", "hidden", "1"),
			("on_hold", "hidden", "1"),
			("payment_schedule", "print_hide", "1"),
			("project", "hidden", "1"),
			("remarks", "hidden", "1"),
			("rounded_total", "hidden", "0"),
			("rounded_total", "print_hide", "0"),
			("scan_barcode", "hidden", "1"),
			("select_print_heading", "hidden", "1"),
			("shipping_rule", "hidden", "1"),
			("subscription_section", "label", "Performance Period"),
			("update_stock", "hidden", "1"),
			("use_company_roundoff_cost_center", "hidden", "1"),
			("use_transaction_date_exchange_rate", "hidden", "1"),
			("write_off", "hidden", "1"),
		],
		"Sales Invoice": [
			(None, "default_print_format", "SO DIN Addressfield"),
			(
				None,
				"field_order",
				'["sales_invoice_info_section", "sales_invoice_info_text", "customer_section", "title", "naming_series", "company", "company_tax_id", "customer", "customer_name", "organization", "tax_id", "buyer_reference", "column_break1", "posting_date", "year_of_settlement", "posting_time", "set_posting_time", "due_date", "column_break_14", "is_pos", "pos_profile", "is_consolidated", "is_return", "return_against", "update_outstanding_for_self", "update_billed_amount_in_sales_order", "update_billed_amount_in_delivery_note", "is_debit_note", "amended_from", "accounting_dimensions_section", "cost_center", "dimension_col_break", "project", "currency_and_price_list", "currency", "conversion_rate", "column_break2", "selling_price_list", "price_list_currency", "plc_conversion_rate", "ignore_pricing_rule", "items_section", "scan_barcode", "update_stock", "column_break_39", "set_warehouse", "set_target_warehouse", "section_break_42", "items", "section_break_30", "total_qty", "total_net_weight", "column_break_32", "base_total", "base_net_total", "column_break_52", "total", "net_total", "taxes_section", "tax_category", "taxes_and_charges", "column_break_38", "shipping_rule", "column_break_55", "incoterm", "named_place", "section_break_40", "taxes", "section_break_43", "base_total_taxes_and_charges", "column_break_47", "total_taxes_and_charges", "totals", "base_grand_total", "base_rounding_adjustment", "base_rounded_total", "base_in_words", "column_break5", "grand_total", "rounding_adjustment", "use_company_roundoff_cost_center", "rounded_total", "in_words", "total_advance", "outstanding_amount", "disable_rounded_total", "section_break_49", "apply_discount_on", "base_discount_amount", "is_cash_or_non_trade_discount", "additional_discount_account", "column_break_51", "additional_discount_percentage", "discount_amount", "sec_tax_breakup", "other_charges_calculation", "pricing_rule_details", "pricing_rules", "packing_list", "packed_items", "product_bundle_help", "time_sheet_list", "timesheets", "section_break_104", "total_billing_hours", "column_break_106", "total_billing_amount", "payments_tab", "payments_section", "cash_bank_account", "payments", "section_break_84", "base_paid_amount", "column_break_86", "paid_amount", "section_break_88", "base_change_amount", "column_break_90", "change_amount", "account_for_change_amount", "advances_section", "allocate_advances_automatically", "only_include_allocated_payments", "get_advances", "advances", "write_off_section", "write_off_amount", "base_write_off_amount", "write_off_outstanding_amount_automatically", "column_break_74", "write_off_account", "write_off_cost_center", "loyalty_points_redemption", "redeem_loyalty_points", "loyalty_points", "loyalty_amount", "column_break_77", "loyalty_program", "dont_create_loyalty_points", "loyalty_redemption_account", "loyalty_redemption_cost_center", "contact_and_address_tab", "address_and_contact", "customer_address", "address_display", "col_break4", "contact_person", "contact_display", "contact_phone", "contact_mobile", "contact_email", "territory", "shipping_address_section", "shipping_address_name", "shipping_address", "shipping_contact", "shipping_contact_display", "shipping_contact_phone", "shipping_contact_mobile", "shipping_contact_email", "shipping_addr_col_break", "dispatch_address_name", "dispatch_address", "company_address_section", "company_address", "company_addr_col_break", "company_contact_person", "company_address_display", "terms_tab", "payment_schedule_section", "ignore_default_payment_terms_template", "payment_terms_template", "payment_schedule", "terms_section_break", "tc_name", "terms", "einvoice_tab", "e_invoice_validation_section", "einvoice_profile", "einvoice_is_correct", "validation_errors", "more_info_tab", "customer_po_details", "po_no", "column_break_23", "po_date", "more_info", "debit_to", "party_account_currency", "is_opening", "column_break8", "unrealized_profit_loss_account", "against_income_account", "sales_team_section_break", "sales_partner", "amount_eligible_for_commission", "column_break10", "commission_rate", "total_commission", "section_break2", "sales_team", "edit_printing_settings", "letter_head", "group_same_items", "column_break_84", "select_print_heading", "language", "subscription_section", "from_date", "auto_repeat", "column_break_140", "to_date", "update_auto_repeat_reference", "more_information", "status", "inter_company_invoice_reference", "campaign", "represents_company", "source", "customer_group", "col_break23", "is_internal_customer", "is_discounted", "remarks", "repost_required", "connections_tab"]',
			),
			(None, "naming_rule", "By script"),
			("additional_discount_account", "hidden", "1"),
			("additional_discount_account", "mandatory_depends_on", ""),
			("advances_section", "hidden", "1"),
			("column_break4", "hidden", "1"),
			("company_address", "hidden", "1"),
			("contact_display", "label", "Billing Contact"),
			("contact_email", "label", "Email (Billing Contact)"),
			("contact_mobile", "label", "Mobile No (Billing Contact)"),
			("contact_person", "fetch_from", "customer.default_billing_contact"),
			("contact_person", "fetch_if_empty", "1"),
			("contact_person", "label", "Billing Contact"),
			("customer_address", "fetch_from", "customer.default_billing_address"),
			("customer_address", "fetch_if_empty", "1"),
			("customer_address", "label", "Billing Address"),
			("customer_po_details", "hidden", "1"),
			("dispatch_address_name", "hidden", "1"),
			("loyalty_points_redemption", "hidden", "1"),
			("naming_series", "options", "ACC-SINV-.YYYY.-\nACC-SINV-RET-.YYYY.-"),
			("outstanding_amount", "in_list_view", "1"),
			(
				"sales_invoice_info_text",
				"options",
				'<p>Infos zum Thema Bestellwesen in den <a href="https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF" target="_blank">LANDA Videotutorials - Bestellwesen</a></p>',
			),
			("sales_team_section_break", "hidden", "1"),
			("section_break_49", "hidden", "1"),
			("section_break2", "hidden", "1"),
			("shipping_address", "label", "Address"),
			("shipping_address_name", "fetch_from", "customer.default_shipping_address"),
			("shipping_address_name", "fetch_if_empty", "1"),
			("shipping_address_name", "label", "Shipping Address"),
			("shipping_contact", "fetch_from", "customer.default_shipping_contact"),
			("shipping_contact", "fetch_if_empty", "1"),
			("subscription_section", "hidden", "1"),
			("tax_id", "hidden", "0"),
			("tax_id", "print_hide", "0"),
			("territory", "hidden", "1"),
			("time_sheet_list", "hidden", "1"),
			("title", "in_list_view", "1"),
			("year_of_settlement", "in_standard_filter", "1"),
		],
		"Sales Invoice Item": [
			("barcode", "hidden", "0"),
			("batch_no", "in_list_view", "0"),
			("discount_account", "hidden", "1"),
			("discount_account", "mandatory_depends_on", ""),
			("qty", "columns", "1"),
			("rate", "columns", "1"),
			("serial_no", "columns", "2"),
			("target_warehouse", "hidden", "1"),
			("warehouse", "in_list_view", "0"),
		],
		"Sales Order": [
			(
				None,
				"field_order",
				'["sales_order_info_section", "sales_order_info_text", "customer_section", "column_break0", "title", "naming_series", "customer", "customer_name", "organization", "tax_id", "order_type", "column_break_7", "transaction_date", "year_of_settlement", "delivery_date", "column_break1", "po_no", "po_date", "company", "skip_delivery_note", "amended_from", "accounting_dimensions_section", "cost_center", "dimension_col_break", "project", "currency_and_price_list", "currency", "conversion_rate", "column_break2", "selling_price_list", "price_list_currency", "plc_conversion_rate", "ignore_pricing_rule", "sec_warehouse", "scan_barcode", "column_break_28", "set_warehouse", "items_section", "items", "section_break_31", "total_qty", "total_net_weight", "column_break_33", "base_total", "base_net_total", "column_break_33a", "total", "net_total", "taxes_section", "tax_category", "taxes_and_charges", "column_break_38", "shipping_rule", "column_break_49", "incoterm", "named_place", "section_break_40", "taxes", "section_break_43", "base_total_taxes_and_charges", "column_break_46", "total_taxes_and_charges", "totals", "base_grand_total", "base_rounding_adjustment", "base_rounded_total", "base_in_words", "column_break3", "grand_total", "rounding_adjustment", "rounded_total", "in_words", "advance_paid", "disable_rounded_total", "section_break_48", "apply_discount_on", "base_discount_amount", "coupon_code", "column_break_50", "additional_discount_percentage", "discount_amount", "sec_tax_breakup", "other_charges_calculation", "packing_list", "packed_items", "pricing_rule_details", "pricing_rules", "contact_info", "billing_address_column", "customer_address", "address_display", "customer_group", "territory", "column_break_84", "contact_person", "contact_display", "contact_phone", "contact_mobile", "contact_email", "shipping_address_column", "shipping_address_name", "shipping_address", "shipping_contact", "shipping_contact_display", "shipping_contact_phone", "shipping_contact_mobile", "shipping_contact_email", "column_break_93", "dispatch_address_name", "dispatch_address", "col_break46", "company_address", "column_break_92", "company_address_display", "payment_schedule_section", "payment_terms_section", "payment_terms_template", "payment_schedule", "terms_section_break", "tc_name", "terms", "more_info", "section_break_78", "status", "delivery_status", "per_delivered", "column_break_81", "per_billed", "per_picked", "billing_status", "sales_team_section_break", "sales_partner", "column_break7", "amount_eligible_for_commission", "commission_rate", "total_commission", "section_break1", "sales_team", "loyalty_points_redemption", "loyalty_points", "column_break_116", "loyalty_amount", "subscription_section", "from_date", "to_date", "column_break_108", "auto_repeat", "update_auto_repeat_reference", "printing_details", "letter_head", "group_same_items", "column_break4", "select_print_heading", "language", "additional_info_section", "is_internal_customer", "represents_company", "column_break_152", "source", "inter_company_order_reference", "campaign", "party_account_currency", "connections_tab"]',
			),
			(None, "naming_rule", "By script"),
			("accounting_dimensions_section", "hidden", "1"),
			("address_display", "label", "Billing Address"),
			("base_rounding_adjustment", "hidden", "1"),
			("company_address", "hidden", "1"),
			("contact_display", "label", "Billing Contact"),
			("contact_email", "label", "Email (Billing Contact)"),
			("contact_mobile", "label", "Mobile No (Billing Contact)"),
			("contact_person", "label", "Billing Contact"),
			(
				"contact_person",
				"read_only_depends_on",
				'eval: !frappe.user.has_role("LANDA Regional Organization Management")',
			),
			("contact_phone", "label", "Phone (Billing Contact)"),
			("conversion_rate", "default", "1"),
			("conversion_rate", "hidden", "1"),
			("conversion_rate", "permlevel", "1"),
			("currency", "permlevel", "1"),
			("currency", "read_only", "1"),
			("currency_and_price_list", "collapsible", "0"),
			("customer_address", "label", "Billing Address"),
			(
				"customer_address",
				"read_only_depends_on",
				'eval: !frappe.user.has_role("LANDA Regional Organization Management")',
			),
			("delivery_date", "hidden", "1"),
			("delivery_date", "in_list_view", "0"),
			("disable_rounded_total", "default", "1"),
			("disable_rounded_total", "hidden", "1"),
			("dispatch_address_name", "hidden", "1"),
			("ignore_pricing_rule", "hidden", "1"),
			("in_words", "hidden", "1"),
			("more_info", "hidden", "1"),
			("naming_series", "options", "SAL-ORD-.YYYY.-"),
			("packing_list", "hidden", "1"),
			("payment_schedule", "hidden", "1"),
			("payment_schedule_section", "hidden", "1"),
			("plc_conversion_rate", "default", "1"),
			("plc_conversion_rate", "hidden", "1"),
			("plc_conversion_rate", "permlevel", "1"),
			("po_no", "hidden", "1"),
			("price_list_currency", "default", "EUR"),
			("price_list_currency", "hidden", "1"),
			("price_list_currency", "permlevel", "1"),
			("printing_details", "hidden", "1"),
			("rounded_total", "hidden", "1"),
			(
				"sales_order_info_text",
				"options",
				'<p>Infos zum Thema Bestellwesen in den <a href="https://youtube.com/playlist?list=PLCG04RYNrML-cMx1lE7DD1gNFmIdE8cZF" target="_blank">LANDA Videotutorials - Bestellwesen</a></p>',
			),
			("sales_team_section_break", "hidden", "1"),
			("scan_barcode", "hidden", "1"),
			("sec_warehouse", "hidden", "1"),
			("section_break_40", "hidden", "1"),
			("section_break_43", "permlevel", "1"),
			("section_break_48", "hidden", "1"),
			("section_break1", "hidden", "1"),
			("shipping_address_name", "label", "Shipping Address"),
			(
				"shipping_address_name",
				"read_only_depends_on",
				'eval: !frappe.user.has_role("LANDA Regional Organization Management")',
			),
			("shipping_rule", "permlevel", "1"),
			("subscription_section", "hidden", "1"),
			("tax_category", "permlevel", "1"),
			("taxes_and_charges", "hidden", "1"),
			("taxes_section", "hidden", "1"),
			("terms_section_break", "hidden", "1"),
			("territory", "hidden", "1"),
			("year_of_settlement", "in_standard_filter", "1"),
		],
		"Sales Order Item": [
			("delivery_date", "hidden", "1"),
			("delivery_date", "in_list_view", "0"),
			("discount_and_margin", "permlevel", "1"),
			("item_code", "columns", "5"),
			("rate", "columns", "1"),
			("rate", "permlevel", "1"),
		],
		"Supplier": [
			(
				None,
				"field_order",
				'["naming_series", "supplier_name", "organization", "country", "column_break0", "supplier_group", "supplier_type", "disabled", "is_transporter", "image", "defaults_section", "default_currency", "default_bank_account", "column_break_10", "default_price_list", "payment_terms", "internal_supplier_section", "is_internal_supplier", "represents_company", "column_break_16", "companies", "column_break2", "supplier_details", "column_break_30", "website", "language", "dashboard_tab", "tax_tab", "tax_id", "column_break_27", "tax_category", "tax_withholding_category", "contact_and_address_tab", "address_contacts", "address_html", "column_break1", "contact_html", "primary_address_and_contact_detail_section", "supplier_primary_contact", "mobile_no", "email_id", "column_break_44", "supplier_primary_address", "primary_address", "accounting_tab", "accounts", "settings_tab", "allow_purchase_invoice_creation_without_purchase_order", "allow_purchase_invoice_creation_without_purchase_receipt", "column_break_54", "is_frozen", "warn_rfqs", "warn_pos", "prevent_rfqs", "prevent_pos", "block_supplier_section", "on_hold", "hold_type", "column_break_59", "release_date"]',
			),
			(None, "quick_entry", "0"),
			("accounts", "hidden", "1"),
			("allow_purchase_invoice_creation_without_purchase_order", "hidden", "1"),
			("allow_purchase_invoice_creation_without_purchase_receipt", "hidden", "1"),
			("contact_and_address_tab", "depends_on", "eval:!doc.__islocal"),
			("default_bank_account", "hidden", "1"),
			("default_currency", "default", "EUR"),
			("default_price_list", "hidden", "1"),
			("is_frozen", "hidden", "1"),
			("is_internal_supplier", "hidden", "1"),
			("is_transporter", "hidden", "1"),
			("language", "default", "de"),
			("naming_series", "hidden", "1"),
			("naming_series", "reqd", "0"),
			("on_hold", "hidden", "1"),
			("supplier_group", "default", "Services"),
			("tax_category", "default", "Vorsteuer"),
			("tax_withholding_category", "hidden", "1"),
		],
		"Tag": [
			(None, "title_field", ""),
		],
		"User": [
			("allowed_in_mentions", "default", "0"),
			("allowed_in_mentions", "permlevel", "1"),
			("document_follow_notify", "default", "0"),
			("document_follow_notify", "permlevel", "1"),
			("email_signature", "permlevel", "1"),
			("logout_all_sessions", "permlevel", "1"),
			("module_profile", "default", "LANDA User"),
			("new_password", "permlevel", "1"),
			("send_me_a_copy", "permlevel", "1"),
			("short_bio", "hidden", "1"),
			("short_bio", "permlevel", "1"),
			("thread_notify", "default", "0"),
			("thread_notify", "permlevel", "1"),
		],
	}
